#!/bin/bash
#TODO add backup option

if [ "$(whoami)" != "root" ]; then
  echo "Must be run as root!"
  exit 1
fi

create_snapshots() {
  for volume in $subvolumes; do
    volume_dir=$(echo "${volume}" | sed -e "s/^@//")
    if [ ! -d "${btrfs_root}/${volume}" ]; then
      echo "$(tput setaf 1)Failed to find subvolume ${volume}, Skipping . . .$(tput sgr0)"
      continue
    fi
    if [ ! -d "${btrfs_root}/snapshots/${volume_dir}" ]; then
      echo "$(tput setaf 1)Failed to find snapshot folder for subvolume ${volume}, Skipping . . .$(tput sgr0)"
      continue
    fi
    if [ -e "${btrfs_root}/snapshots/${volume_dir}/${timestamp}" ]; then
      echo "$(tput setaf 1)There already exists a snapshot for this date of subvolume ${volume}, Skipping . . .$(tput sgr0)"
      continue
    fi

    btrfs subvolume snapshot -r "${btrfs_root}/${volume}" "${btrfs_root}/snapshots/${volume_dir}/${timestamp}"
    if [[ $? == 0 ]]; then
      echo "$(tput setaf 2)Created snapshot of ${volume}$(tput sgr0)"
    else
      echo "$(tput setaf 1)Failed to create snapshot of ${volume}!$(tput sgr0)"
    fi
  done
}


timestamp=$(date +%y-%m-%d)


echo -e "Creating snapshots of foxlair-home . . .\n"

btrfs_root="/mnt/subvolumes-home"

echo "Mounting ${btrfs_root} . . ."
if ! mount $btrfs_root; then
  echo "$(tput setaf 1)Failed to mount ${btrfs_root}! Assuming already mounted . . .$(tput sgr0)"
fi

subvolumes="
  documents
  fzi
  home
  kamaro
  media
  studium
"
create_snapshots

echo -e "Finished creating snapshots of foxlair-home. \n"

tree -L 2 ${btrfs_root}/snapshots


echo -e "\nCreating snapshots of foxlair-linux . . .\n"

btrfs_root="/mnt/subvolumes-linux"

echo "Mounting ${btrfs_root} . . ."
if ! mount $btrfs_root; then
  echo "$(tput setaf 1)Failed to mount ${btrfs_root}! Assuming already mounted . . .$(tput sgr0)"
fi

subvolumes="
  arch-root
  arch-root/etc
"
create_snapshots

echo -e "Finished creating snapshots of foxlair-linux. \n"

tree -L 2 ${btrfs_root}/snapshots
